module.exports = [
  'Desconocido',
  'Banesco',
  `Banco de Venezuela`,
  `BBVA Provincial`,
  `Banco Mercantil`,
  `BOD`,
  `Banco Bicentenario`,
  `Bancaribe`,
  `BNC`,
  `Banco del Tesoro`,
  `Bancaribe`,
  `Banco Exterior`,
  `BFC`,
  `Sofitasa`,
  `Bancrecer`,
  `Banplus`,
  `Banco Plaza`,
  `Banco Caroni`,
  `DELSUR`,
];
